# make environment
PYTHON = /usr/local/bin/python
ECHO = echo

# installation root prefix
PREFIX = /usr/local

# cctbx.python
CCTBX_PYTHON = /usr/local/cctbx-svn/build/bin/cctbx.python

# build directories

# documentation source
DOCDIR = docs

# build directory
BUILDDIR = build

# built html documentation directory
HTMLDIR = html

# built pdf and zip documentation directory
DOCDEST = .

# name of template file for license
LICENSE_TEMPLATE = LICENSE-BSD.tmplt
